name: Release to NPM
on:
  push:
    branches: [callum/test-changes]
jobs:
  publish:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install modules
        run: rm -rf node_modules && yarn install --frozen-lockfile
      - name: Build 🔧
        run: yarn build
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      # - name: Semantic Release
      #   uses: cycjimmy/semantic-release-action@v2
      #   with:
      #     extra_plugins: |
      #       @semantic-release/git
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GH_RELEASE_TOKEN }}
      #     NPM_TOKEN: ${{ secrets.NPM_TOKEN }}


      # 